image: maven:latest

stages:
  - compile
  - test
  - build

variables:
  MAVEN_OPTS: "--batch-mode  -Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2/
    - target/

compile:
  stage: compile
  script:
    - mvn $MAVEN_OPTS -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "footapi"
    MYSQL_ROOT_PASSWORD: "1azerty."
  script:
    - mvn $MAVEN_OPTS -P gitlab test

build_jar:
  stage: build
  when: manual
  script:
    - mvn $MAVEN_OPTS -Dmaven.test.skip=true package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days

build_image_dockerhub:
  stage: build
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn $MAVEN_OPTS -Dmaven.test.skip=true -P dockerhub install


build_image_googlecloud:
  stage: build
  when: manual
  services:
    - docker:dind
  variables:
    GOOGLE_APPLICATION_CREDENTIALS: $CI_PROJECT_DIR/credentials.json
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn -X --batch-mode -Dmaven.test.skip=true -P googlecloud install
