image: maven:latest

stages:
  - compile
  - test

cache:
  paths:
    - .m2/
    - target/

variables:
  BUILD_VERSION: ""

compile:
  stage: compile
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "gitlab"
    MYSQL_ROOT_PASSWORD: "gitlab"
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab test

#build:
#  stage: build
#  script:
#    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab -Dmaven.test.skip=true clean package
#    - BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
#  artifacts:
#    paths:
#     - target/${APP_NAME}-${BUILD_VERSION}.jar
#    expire_in: 30 days
#
#create_image:
#  image: docker:latest
#  stage: create_image
#  services:
#    - docker:dind
#
#  when: manual
#  before_script:
#    - docker login -u robinln -p 220090Atm22!
#  script:
#    - echo $BUILD_VERSION
#    - docker build \
#      --build-arg BUILD_VERSION=$BUILD_VERSION \
#      --build-arg APP_NAME="myFootApi" \
#      -t app \
#      -f docker/Dockerfile .
#    - docker tag app robinln/my-foot-api:${BUILD_VERSION}
#    - docker push robinln/my-foot-api:${BUILD_VERSION}
