before_script:
  - echo "Start !"

after_script:
  - echo "End !"

services:
  - mysql:latest

stages:
  - build
  - connect
  - test
  - package
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MYSQL_DATABASE_NAME: "gitlab"
  MYSQL_ROOT_PASSWORD: "gitlab"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

connect:
  stage: connect
  image: mysql
  before_script:
    - mysql --version
  script:
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD"
    - CREATE DATABASE $MYSQL_DATABASE_NAME;

test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS test

package:
  stage: package
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths: [target/basecamp-0.0.1.war]


deploy_test:
  stage: deploy
  script:
    - echo "########   To be defined   ########"
  environment: staging

deploy_prod:
  stage: deploy
  script:
    - echo "########   To be defined   ########"
  only:
    - master
  environment: production
