stages:
  - build
  - image

cache:
  paths:
    - .m2/
    - target/
    - tmp/


build_jar:
  image: maven:latest
  stage: build
  before_script:
    - echo '#!/bin/sh' > tmp/varriables.sh
    - chmod +x tmp/varriables.sh
  script:
    - mvn --batch-mode -Dmaven.repo.local=.m2 -Dmaven.test.skip=true package
    - echo export VERSION="$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> tmp/varriables.sh
    - echo export BUILD_NAME="$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> tmp/varriables.sh
    - echo export PROJECT_NAME="$(mvn org.apache.maven.plugins:maven-help-plugin:3.1.0:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> tmp/varriables.sh
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days

build_image_dockerhub:
  image: docker:latest
  stage: image
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - /bin/sh tmp/varriables.sh
    - echo "$DOCKER_TOKKEN" | docker login --username $DOCKER_USER --password-stdin
  script:
    - ./tmp/varriables.sh
    - cat tmp/varriables.sh
    - echo target/${BUILD_NAME}.jar
    - echo ${DOCKER_USER}
    - echo ${PROJECT_NAME}
    - echo ${VERSION}
    - echo $DOCKER_USER
    - echo $PROJECT_NAME
    - echo $VERSION
    - ls target
    - docker build --build-arg JAR_FILE=target/${BUILD_NAME}.jar \
      -t ${DOCKER_USER}/${PROJECT_NAME}:${VERSION} \
      -f docker/Dockerfile .
    - docker push ${DOCKER_USER}/${PROJECT_NAME}:${VERSION}


build_image_googlecloud:
  image: docker:latest
  stage: image
  when: manual
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_SERVER: eu.gcr.io
  script:
    - docker build --build-arg JAR_FILE=target/${BUILD_NAME}.jar \
      -t ${DOCKER_SERVER}/${DOCKER_USER}/${PROJECT_NAME}:${VERSION} \
      -f docker/Dockerfile .
    - docker push ${DOCKER_SERVER}/${DOCKER_USER}/${PROJECT_NAME}:${VERSION}
