image: maven:latest

stages:
  - compile
  - test
  - image_docker

cache:
  paths:
    - .m2/
    - target/

compile:
  stage: compile
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "gitlab"
    MYSQL_ROOT_PASSWORD: "gitlab"
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab test

image_docker:
  stage: image_docker
  when: manual
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true install
