stages:
  - test
  - deploy

image: maven:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "gitlab"
  MYSQL_ROOT_PASSWORD: "gitlab"
  MAVEN_OPTION: "-P gitlab"

test:
  stage: test
  script:
    - mvn $MAVEN_OPTION test

deploy_val:
  stage: deploy
  script:
    - echo "Deploy to validation server"
    - mvn --version
  environment:
    name: validation
  when: manual
  only:
    - develop
    - /^feature.*$/
    - /^fix.*$/

deploy_rec:
  stage: deploy
  script:
    - echo "Deploy to recette server"
    - mvn --version
  environment:
    name: recette
  when: manual
  only:
    - /^release.*$/

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
  when: manual
  only:
    - master
