image: maven:latest

stages:
  - build
  - test
  - package
  - deploy

variables:
  MYSQL_DATABASE: gitlab
  MYSQL_ROOT_PASSWORD: gitlab
  SPRING_PROFILES_ACTIVE: gitlab

build:
  stage: build
  script:
    - mvn clean compile

test:
  services:
    - mysql:latest
  stage: test
  script:
    - mvn test

package:
  stage: package
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - echo "########   To be defined   ########"
