image: maven:latest

stages:
  - compile
  - test
  - install

cache:
  paths:
    - .m2/
    - target/

compile:
  stage: compile
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "gitlab"
    MYSQL_ROOT_PASSWORD: "gitlab"
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab test

install:
  stage: install
  services:
    - docker:dind
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true install
