stages:
  - build
  - test
  - package
  - deploy

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: gitlab
  MYSQL_ROOT_PASSWORD: gitlab
  SPRING_PROFILES_ACTIVE: gitlab

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn test

package:
  stage: package
  image: maven:latest
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - echo "########   To be defined   ########"
