stages:
  - build
  - test
  - package
  - deploy

variables:
  MYSQL_DATABASE: "gitlab"
  MYSQL_ROOT_PASSWORD: "gitlab"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean compile

test:
  stage: test
  image: maven:latest
  services:
    - mysql:latest
  script:
    - mvn test

package:
  stage: package
  image: maven:latest
  script:
    - mvn package

deploy:
  stage: deploy
  script:
    - echo "########   To be defined   ########"
  environment: staging

