stages:
  - compile
  - test
  - build
  - create_image

cache:
  paths:
    - .m2/repository
    - targer

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: "gitlab"
  MYSQL_ROOT_PASSWORD: "gitlab"
  MAVEN_OPTION: "-P gitlab"

compile:
  stage: compile
  image: maven:latest
  script:
    - mvn $MAVEN_OPTION compile

test:
  stage: test
  image: maven:latest
  script:
    - mvn $MAVEN_OPTION test

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_OPTION package

create_image:
  stage: create
  image: docker:latest
  script:
    - docker build -t app -f docker/Dockerfile .
  environment:
    name: recette
  only:
    - /^release.*$/
