image: maven:latest

stages:
  - compile
  - test
  - build

cache:
  paths:
    - .m2/
    - target/

compile:
  stage: compile
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "gitlab"
    MYSQL_ROOT_PASSWORD: "gitlab"
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -P gitlab test

jar:
  stage: build
  variables:
    - BUILD_VERSION: ""
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true package
    - BUILD_VERSION=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)
  artifacts:
    paths:
     - target/${APP_NAME}-${BUILD_VERSION}.jar
    expire_in: 30 days

image_docker:
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true install
