image: maven:latest

stages:
  - compile
  - test
  - build
  - create_image

cache:
  paths:
    - .m2/
    - target/

services:
  - mysql:latest
  - docker:dind

variables:
  MYSQL_DATABASE: "gitlab"
  MYSQL_ROOT_PASSWORD: "gitlab"
  MAVEN_OPTION: "-Dmaven.repo.local=.m2 -P gitlab"

compile:
  stage: compile
  script:
    - mvn $MAVEN_OPTION compile

test:
  stage: test
  script:
    - mvn $MAVEN_OPTION test

build:
  stage: build
  script:
    - mvn $MAVEN_OPTION package
  artifacts:
    name: targer/app.jar
    expire_in: 30 days

create_image:
  stage: create_image
  script:
    - docker build -t app -f docker/Dockerfile .
