image: maven:latest

stages:
  - compile
  - test
  - build

cache:
  paths:
    - .m2/
    - target/

compile:
  stage: compile
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "footapi"
    MYSQL_ROOT_PASSWORD: "1azerty."
  script:
    - mvn -Dmaven.repo.local=.m2 -Dspring.profiles.active=gitlab --batch-mode test

build:
  stage: build
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true package

build_jar:
  stage: build
  when: manual
  needs: test
  script:
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days

build_image:
  stage: build
  when: manual
  needs: test
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn -Dmaven.repo.local=.m2 --batch-mode -Dmaven.test.skip=true install
