image: maven:latest

stages:
  - compile
  - test
  - build

cache:
  paths:
    - $HOME/.m2/
    - target/

compile:
  stage: compile
  script:
    - mvn --batch-mode -Dmaven.test.skip=true compile

test:
  stage: test
  services:
    - mysql:latest
  variables:
    MYSQL_DATABASE: "footapi"
    MYSQL_ROOT_PASSWORD: "1azerty."
  script:
    - mvn --batch-mode -P gitlab test

build_jar:
  stage: build
  when: manual
  script:
    - mvn --batch-mode -Dmaven.test.skip=true package
  artifacts:
    paths:
      - target/*.jar
    expire_in: 30 days

build_image_dockerhub:
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn --batch-mode -Dmaven.test.skip=true -P dockerhub install


build_image_googlecloud:
  stage: build
  when: manual
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375
    - mvn --batch-mode -Dmaven.test.skip=true -P googlecloud install
