spring:
  cloud.gcp.sql:
    instance-connection-name: my-foot-api:europe-north1:my-foot-bdd-prod
    database-name: footapi
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
  datasource:
    username: root
    password: rvEgz9l1kc81wA07
    driver-class-name: com.mysql.cj.jdbc.Driver

football-data-api:
  basePath: https://api.football-data.org/v2/
  apiKey: 5a2c20184d344d278b11894ab7e3ede1
  level: BODY

app:
  secret: prod
