spring:
  jpa:
    hibernate.ddl-auto: none
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/gitlab
    username: root
    password: 1azerty.

football-data-api:
  basePath: https://api.football-data.org/v2/
  apiKey: 5a2c20184d344d278b11894ab7e3ede1
  level: BODY
