spring:
  cloud.gcp.sql:
    instance-connection-name: mysql
    database-name: footapi
  jpa:
    hibernate.ddl-auto: create
    open-in-view: true
  datasource:
    url: jdbc:mysql://mysql:3306/footapi
    username: root
    password: 1azerty.

football-data-api:
  basePath: https://api.football-data.org/v2/
  apiKey: 5a2c20184d344d278b11894ab7e3ede1
  level: BODY

app:
  secret: gitlab
