spring:
  jpa:
    hibernate.ddl-auto: update
    open-in-view: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://35.228.228.114:3306/footapi
    username: root
    password: rvEgz9l1kc81wA07

football-data-api:
  basePath: https://api.football-data.org/v2/
  apiKey: 5a2c20184d344d278b11894ab7e3ede1
  level: BODY

app:
  secret: prod
